openapi: 3.0.0
info:
  description: kuucode API
  title: kuucode
  version: 1.0.0
servers:
- url: /
paths:
  /session:
    post:
      operationId: createSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSessionRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
          description: Session created
      summary: Create a new session
  /session/{id}/message:
    post:
      operationId: sendMessage
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: Message sent
      summary: Send a message to a session
components:
  schemas:
    CreateSessionRequest:
      example:
        system: system
        providerID: providerID
        model: model
      properties:
        providerID:
          type: string
        model:
          type: string
        system:
          type: string
      type: object
    Session:
      example:
        providerID: providerID
        model: model
        id: id
      properties:
        id:
          type: string
        providerID:
          type: string
        model:
          type: string
      type: object
    SendMessageRequest:
      example:
        files:
        - path: path
          content: content
        - path: path
          content: content
        text: text
      properties:
        text:
          type: string
        files:
          items:
            $ref: "#/components/schemas/SendMessageRequest_files_inner"
          type: array
      type: object
    SendMessageRequest_files_inner:
      example:
        path: path
        content: content
      properties:
        path:
          type: string
        content:
          type: string
      type: object
