openapi: 3.0.0
info:
  description: kuuzuki API
  title: kuuzuki
  version: 1.0.0
servers:
- url: /
paths:
  /session:
    post:
      operationId: createSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSessionRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
          description: Session created
      summary: Create a new session
  /session/{id}/message:
    post:
      operationId: sendMessage
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: Message sent
      summary: Send a message to a session
components:
  schemas:
    CreateSessionRequest:
      example:
        system: system
        providerID: providerID
        model: model
      properties:
        providerID:
          type: string
        model:
          type: string
        system:
          type: string
      type: object
    Session:
      example:
        providerID: providerID
        model: model
        id: id
      properties:
        id:
          type: string
        providerID:
          type: string
        model:
          type: string
      type: object
    SendMessageRequest:
      example:
        files:
        - path: path
          content: content
        - path: path
          content: content
        text: text
      properties:
        text:
          type: string
        files:
          items:
            $ref: "#/components/schemas/SendMessageRequest_files_inner"
          type: array
      type: object
    App:
      properties:
        hostname:
          type: string
        git:
          type: boolean
        path:
          $ref: "#/components/schemas/App_path"
        time:
          $ref: "#/components/schemas/App_time"
      type: object
    Mode:
      properties:
        model:
          type: string
        prompt:
          type: string
        tools:
          additionalProperties:
            type: boolean
          type: object
      type: object
    Model:
      properties:
        id:
          type: string
        name:
          type: string
        release_date:
          type: string
        attachment:
          type: boolean
        reasoning:
          type: boolean
        temperature:
          type: boolean
        tool_call:
          type: boolean
        cost:
          $ref: "#/components/schemas/Model_cost"
        limit:
          $ref: "#/components/schemas/Model_limit"
        options:
          additionalProperties: true
          type: object
      type: object
    Provider:
      properties:
        api:
          type: string
        name:
          type: string
        env:
          items:
            type: string
          type: array
        id:
          type: string
        npm:
          type: string
        models:
          additionalProperties:
            $ref: "#/components/schemas/Model"
          type: object
      type: object
    SendMessageRequest_files_inner:
      example:
        path: path
        content: content
      properties:
        path:
          type: string
        content:
          type: string
      type: object
    App_path:
      properties:
        config:
          type: string
        data:
          type: string
        root:
          type: string
        cwd:
          type: string
        state:
          type: string
      type: object
    App_time:
      properties:
        initialized:
          type: number
      type: object
    Model_cost:
      properties:
        input:
          type: number
        output:
          type: number
        cache_read:
          type: number
        cache_write:
          type: number
      type: object
    Model_limit:
      properties:
        context:
          type: number
        output:
          type: number
      type: object
