/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MatchSubmatchesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatchSubmatchesInner{}

// MatchSubmatchesInner struct for MatchSubmatchesInner
type MatchSubmatchesInner struct {
	Match MatchPath `json:"match"`
	Start float32 `json:"start"`
	End float32 `json:"end"`
}

type _MatchSubmatchesInner MatchSubmatchesInner

// NewMatchSubmatchesInner instantiates a new MatchSubmatchesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchSubmatchesInner(match MatchPath, start float32, end float32) *MatchSubmatchesInner {
	this := MatchSubmatchesInner{}
	this.Match = match
	this.Start = start
	this.End = end
	return &this
}

// NewMatchSubmatchesInnerWithDefaults instantiates a new MatchSubmatchesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchSubmatchesInnerWithDefaults() *MatchSubmatchesInner {
	this := MatchSubmatchesInner{}
	return &this
}

// GetMatch returns the Match field value
func (o *MatchSubmatchesInner) GetMatch() MatchPath {
	if o == nil {
		var ret MatchPath
		return ret
	}

	return o.Match
}

// GetMatchOk returns a tuple with the Match field value
// and a boolean to check if the value has been set.
func (o *MatchSubmatchesInner) GetMatchOk() (*MatchPath, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Match, true
}

// SetMatch sets field value
func (o *MatchSubmatchesInner) SetMatch(v MatchPath) {
	o.Match = v
}

// GetStart returns the Start field value
func (o *MatchSubmatchesInner) GetStart() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *MatchSubmatchesInner) GetStartOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *MatchSubmatchesInner) SetStart(v float32) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *MatchSubmatchesInner) GetEnd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *MatchSubmatchesInner) GetEndOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *MatchSubmatchesInner) SetEnd(v float32) {
	o.End = v
}

func (o MatchSubmatchesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatchSubmatchesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["match"] = o.Match
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

func (o *MatchSubmatchesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"match",
		"start",
		"end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMatchSubmatchesInner := _MatchSubmatchesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMatchSubmatchesInner)

	if err != nil {
		return err
	}

	*o = MatchSubmatchesInner(varMatchSubmatchesInner)

	return err
}

type NullableMatchSubmatchesInner struct {
	value *MatchSubmatchesInner
	isSet bool
}

func (v NullableMatchSubmatchesInner) Get() *MatchSubmatchesInner {
	return v.value
}

func (v *NullableMatchSubmatchesInner) Set(val *MatchSubmatchesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchSubmatchesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchSubmatchesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchSubmatchesInner(val *MatchSubmatchesInner) *NullableMatchSubmatchesInner {
	return &NullableMatchSubmatchesInner{value: val, isSet: true}
}

func (v NullableMatchSubmatchesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchSubmatchesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


