/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostSessionByIdInitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostSessionByIdInitRequest{}

// PostSessionByIdInitRequest struct for PostSessionByIdInitRequest
type PostSessionByIdInitRequest struct {
	MessageID string `json:"messageID"`
	ProviderID string `json:"providerID"`
	ModelID string `json:"modelID"`
}

type _PostSessionByIdInitRequest PostSessionByIdInitRequest

// NewPostSessionByIdInitRequest instantiates a new PostSessionByIdInitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostSessionByIdInitRequest(messageID string, providerID string, modelID string) *PostSessionByIdInitRequest {
	this := PostSessionByIdInitRequest{}
	this.MessageID = messageID
	this.ProviderID = providerID
	this.ModelID = modelID
	return &this
}

// NewPostSessionByIdInitRequestWithDefaults instantiates a new PostSessionByIdInitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostSessionByIdInitRequestWithDefaults() *PostSessionByIdInitRequest {
	this := PostSessionByIdInitRequest{}
	return &this
}

// GetMessageID returns the MessageID field value
func (o *PostSessionByIdInitRequest) GetMessageID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageID
}

// GetMessageIDOk returns a tuple with the MessageID field value
// and a boolean to check if the value has been set.
func (o *PostSessionByIdInitRequest) GetMessageIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageID, true
}

// SetMessageID sets field value
func (o *PostSessionByIdInitRequest) SetMessageID(v string) {
	o.MessageID = v
}

// GetProviderID returns the ProviderID field value
func (o *PostSessionByIdInitRequest) GetProviderID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderID
}

// GetProviderIDOk returns a tuple with the ProviderID field value
// and a boolean to check if the value has been set.
func (o *PostSessionByIdInitRequest) GetProviderIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderID, true
}

// SetProviderID sets field value
func (o *PostSessionByIdInitRequest) SetProviderID(v string) {
	o.ProviderID = v
}

// GetModelID returns the ModelID field value
func (o *PostSessionByIdInitRequest) GetModelID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelID
}

// GetModelIDOk returns a tuple with the ModelID field value
// and a boolean to check if the value has been set.
func (o *PostSessionByIdInitRequest) GetModelIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelID, true
}

// SetModelID sets field value
func (o *PostSessionByIdInitRequest) SetModelID(v string) {
	o.ModelID = v
}

func (o PostSessionByIdInitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostSessionByIdInitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageID"] = o.MessageID
	toSerialize["providerID"] = o.ProviderID
	toSerialize["modelID"] = o.ModelID
	return toSerialize, nil
}

func (o *PostSessionByIdInitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageID",
		"providerID",
		"modelID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostSessionByIdInitRequest := _PostSessionByIdInitRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostSessionByIdInitRequest)

	if err != nil {
		return err
	}

	*o = PostSessionByIdInitRequest(varPostSessionByIdInitRequest)

	return err
}

type NullablePostSessionByIdInitRequest struct {
	value *PostSessionByIdInitRequest
	isSet bool
}

func (v NullablePostSessionByIdInitRequest) Get() *PostSessionByIdInitRequest {
	return v.value
}

func (v *NullablePostSessionByIdInitRequest) Set(val *PostSessionByIdInitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostSessionByIdInitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostSessionByIdInitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostSessionByIdInitRequest(val *PostSessionByIdInitRequest) *NullablePostSessionByIdInitRequest {
	return &NullablePostSessionByIdInitRequest{value: val, isSet: true}
}

func (v NullablePostSessionByIdInitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostSessionByIdInitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


