/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
)

// checks if the EventSessionErrorProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSessionErrorProperties{}

// EventSessionErrorProperties struct for EventSessionErrorProperties
type EventSessionErrorProperties struct {
	SessionID *string `json:"sessionID,omitempty"`
	Error *AssistantMessageError `json:"error,omitempty"`
}

// NewEventSessionErrorProperties instantiates a new EventSessionErrorProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSessionErrorProperties() *EventSessionErrorProperties {
	this := EventSessionErrorProperties{}
	return &this
}

// NewEventSessionErrorPropertiesWithDefaults instantiates a new EventSessionErrorProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSessionErrorPropertiesWithDefaults() *EventSessionErrorProperties {
	this := EventSessionErrorProperties{}
	return &this
}

// GetSessionID returns the SessionID field value if set, zero value otherwise.
func (o *EventSessionErrorProperties) GetSessionID() string {
	if o == nil || IsNil(o.SessionID) {
		var ret string
		return ret
	}
	return *o.SessionID
}

// GetSessionIDOk returns a tuple with the SessionID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSessionErrorProperties) GetSessionIDOk() (*string, bool) {
	if o == nil || IsNil(o.SessionID) {
		return nil, false
	}
	return o.SessionID, true
}

// HasSessionID returns a boolean if a field has been set.
func (o *EventSessionErrorProperties) HasSessionID() bool {
	if o != nil && !IsNil(o.SessionID) {
		return true
	}

	return false
}

// SetSessionID gets a reference to the given string and assigns it to the SessionID field.
func (o *EventSessionErrorProperties) SetSessionID(v string) {
	o.SessionID = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *EventSessionErrorProperties) GetError() AssistantMessageError {
	if o == nil || IsNil(o.Error) {
		var ret AssistantMessageError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSessionErrorProperties) GetErrorOk() (*AssistantMessageError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *EventSessionErrorProperties) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given AssistantMessageError and assigns it to the Error field.
func (o *EventSessionErrorProperties) SetError(v AssistantMessageError) {
	o.Error = &v
}

func (o EventSessionErrorProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSessionErrorProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionID) {
		toSerialize["sessionID"] = o.SessionID
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableEventSessionErrorProperties struct {
	value *EventSessionErrorProperties
	isSet bool
}

func (v NullableEventSessionErrorProperties) Get() *EventSessionErrorProperties {
	return v.value
}

func (v *NullableEventSessionErrorProperties) Set(val *EventSessionErrorProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSessionErrorProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSessionErrorProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSessionErrorProperties(val *EventSessionErrorProperties) *NullableEventSessionErrorProperties {
	return &NullableEventSessionErrorProperties{value: val, isSet: true}
}

func (v NullableEventSessionErrorProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSessionErrorProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


