/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolStateCompleted type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolStateCompleted{}

// ToolStateCompleted struct for ToolStateCompleted
type ToolStateCompleted struct {
	Status string `json:"status"`
	Input map[string]interface{} `json:"input"`
	Output string `json:"output"`
	Title string `json:"title"`
	Metadata map[string]interface{} `json:"metadata"`
	Time ToolStateCompletedTime `json:"time"`
}

type _ToolStateCompleted ToolStateCompleted

// NewToolStateCompleted instantiates a new ToolStateCompleted object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolStateCompleted(status string, input map[string]interface{}, output string, title string, metadata map[string]interface{}, time ToolStateCompletedTime) *ToolStateCompleted {
	this := ToolStateCompleted{}
	this.Status = status
	this.Input = input
	this.Output = output
	this.Title = title
	this.Metadata = metadata
	this.Time = time
	return &this
}

// NewToolStateCompletedWithDefaults instantiates a new ToolStateCompleted object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolStateCompletedWithDefaults() *ToolStateCompleted {
	this := ToolStateCompleted{}
	return &this
}

// GetStatus returns the Status field value
func (o *ToolStateCompleted) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompleted) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ToolStateCompleted) SetStatus(v string) {
	o.Status = v
}

// GetInput returns the Input field value
func (o *ToolStateCompleted) GetInput() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompleted) GetInputOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// SetInput sets field value
func (o *ToolStateCompleted) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetOutput returns the Output field value
func (o *ToolStateCompleted) GetOutput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompleted) GetOutputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *ToolStateCompleted) SetOutput(v string) {
	o.Output = v
}

// GetTitle returns the Title field value
func (o *ToolStateCompleted) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompleted) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ToolStateCompleted) SetTitle(v string) {
	o.Title = v
}

// GetMetadata returns the Metadata field value
func (o *ToolStateCompleted) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompleted) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *ToolStateCompleted) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetTime returns the Time field value
func (o *ToolStateCompleted) GetTime() ToolStateCompletedTime {
	if o == nil {
		var ret ToolStateCompletedTime
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompleted) GetTimeOk() (*ToolStateCompletedTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *ToolStateCompleted) SetTime(v ToolStateCompletedTime) {
	o.Time = v
}

func (o ToolStateCompleted) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolStateCompleted) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["input"] = o.Input
	toSerialize["output"] = o.Output
	toSerialize["title"] = o.Title
	toSerialize["metadata"] = o.Metadata
	toSerialize["time"] = o.Time
	return toSerialize, nil
}

func (o *ToolStateCompleted) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"input",
		"output",
		"title",
		"metadata",
		"time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolStateCompleted := _ToolStateCompleted{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolStateCompleted)

	if err != nil {
		return err
	}

	*o = ToolStateCompleted(varToolStateCompleted)

	return err
}

type NullableToolStateCompleted struct {
	value *ToolStateCompleted
	isSet bool
}

func (v NullableToolStateCompleted) Get() *ToolStateCompleted {
	return v.value
}

func (v *NullableToolStateCompleted) Set(val *ToolStateCompleted) {
	v.value = val
	v.isSet = true
}

func (v NullableToolStateCompleted) IsSet() bool {
	return v.isSet
}

func (v *NullableToolStateCompleted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolStateCompleted(val *ToolStateCompleted) *NullableToolStateCompleted {
	return &NullableToolStateCompleted{value: val, isSet: true}
}

func (v NullableToolStateCompleted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolStateCompleted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


