/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventMessageRemoved type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventMessageRemoved{}

// EventMessageRemoved struct for EventMessageRemoved
type EventMessageRemoved struct {
	Type string `json:"type"`
	Properties EventMessageRemovedProperties `json:"properties"`
}

type _EventMessageRemoved EventMessageRemoved

// NewEventMessageRemoved instantiates a new EventMessageRemoved object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventMessageRemoved(type_ string, properties EventMessageRemovedProperties) *EventMessageRemoved {
	this := EventMessageRemoved{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventMessageRemovedWithDefaults instantiates a new EventMessageRemoved object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventMessageRemovedWithDefaults() *EventMessageRemoved {
	this := EventMessageRemoved{}
	return &this
}

// GetType returns the Type field value
func (o *EventMessageRemoved) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventMessageRemoved) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventMessageRemoved) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventMessageRemoved) GetProperties() EventMessageRemovedProperties {
	if o == nil {
		var ret EventMessageRemovedProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventMessageRemoved) GetPropertiesOk() (*EventMessageRemovedProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventMessageRemoved) SetProperties(v EventMessageRemovedProperties) {
	o.Properties = v
}

func (o EventMessageRemoved) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventMessageRemoved) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventMessageRemoved) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventMessageRemoved := _EventMessageRemoved{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventMessageRemoved)

	if err != nil {
		return err
	}

	*o = EventMessageRemoved(varEventMessageRemoved)

	return err
}

type NullableEventMessageRemoved struct {
	value *EventMessageRemoved
	isSet bool
}

func (v NullableEventMessageRemoved) Get() *EventMessageRemoved {
	return v.value
}

func (v *NullableEventMessageRemoved) Set(val *EventMessageRemoved) {
	v.value = val
	v.isSet = true
}

func (v NullableEventMessageRemoved) IsSet() bool {
	return v.isSet
}

func (v *NullableEventMessageRemoved) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventMessageRemoved(val *EventMessageRemoved) *NullableEventMessageRemoved {
	return &NullableEventMessageRemoved{value: val, isSet: true}
}

func (v NullableEventMessageRemoved) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventMessageRemoved) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


