/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RangeStart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RangeStart{}

// RangeStart struct for RangeStart
type RangeStart struct {
	Line float32 `json:"line"`
	Character float32 `json:"character"`
}

type _RangeStart RangeStart

// NewRangeStart instantiates a new RangeStart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRangeStart(line float32, character float32) *RangeStart {
	this := RangeStart{}
	this.Line = line
	this.Character = character
	return &this
}

// NewRangeStartWithDefaults instantiates a new RangeStart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRangeStartWithDefaults() *RangeStart {
	this := RangeStart{}
	return &this
}

// GetLine returns the Line field value
func (o *RangeStart) GetLine() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Line
}

// GetLineOk returns a tuple with the Line field value
// and a boolean to check if the value has been set.
func (o *RangeStart) GetLineOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line, true
}

// SetLine sets field value
func (o *RangeStart) SetLine(v float32) {
	o.Line = v
}

// GetCharacter returns the Character field value
func (o *RangeStart) GetCharacter() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Character
}

// GetCharacterOk returns a tuple with the Character field value
// and a boolean to check if the value has been set.
func (o *RangeStart) GetCharacterOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Character, true
}

// SetCharacter sets field value
func (o *RangeStart) SetCharacter(v float32) {
	o.Character = v
}

func (o RangeStart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RangeStart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["line"] = o.Line
	toSerialize["character"] = o.Character
	return toSerialize, nil
}

func (o *RangeStart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"line",
		"character",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRangeStart := _RangeStart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRangeStart)

	if err != nil {
		return err
	}

	*o = RangeStart(varRangeStart)

	return err
}

type NullableRangeStart struct {
	value *RangeStart
	isSet bool
}

func (v NullableRangeStart) Get() *RangeStart {
	return v.value
}

func (v *NullableRangeStart) Set(val *RangeStart) {
	v.value = val
	v.isSet = true
}

func (v NullableRangeStart) IsSet() bool {
	return v.isSet
}

func (v *NullableRangeStart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRangeStart(val *RangeStart) *NullableRangeStart {
	return &NullableRangeStart{value: val, isSet: true}
}

func (v NullableRangeStart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRangeStart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


