/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventSessionUpdated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSessionUpdated{}

// EventSessionUpdated struct for EventSessionUpdated
type EventSessionUpdated struct {
	Type string `json:"type"`
	Properties EventSessionUpdatedProperties `json:"properties"`
}

type _EventSessionUpdated EventSessionUpdated

// NewEventSessionUpdated instantiates a new EventSessionUpdated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSessionUpdated(type_ string, properties EventSessionUpdatedProperties) *EventSessionUpdated {
	this := EventSessionUpdated{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventSessionUpdatedWithDefaults instantiates a new EventSessionUpdated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSessionUpdatedWithDefaults() *EventSessionUpdated {
	this := EventSessionUpdated{}
	return &this
}

// GetType returns the Type field value
func (o *EventSessionUpdated) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventSessionUpdated) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventSessionUpdated) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventSessionUpdated) GetProperties() EventSessionUpdatedProperties {
	if o == nil {
		var ret EventSessionUpdatedProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventSessionUpdated) GetPropertiesOk() (*EventSessionUpdatedProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventSessionUpdated) SetProperties(v EventSessionUpdatedProperties) {
	o.Properties = v
}

func (o EventSessionUpdated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSessionUpdated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventSessionUpdated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventSessionUpdated := _EventSessionUpdated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventSessionUpdated)

	if err != nil {
		return err
	}

	*o = EventSessionUpdated(varEventSessionUpdated)

	return err
}

type NullableEventSessionUpdated struct {
	value *EventSessionUpdated
	isSet bool
}

func (v NullableEventSessionUpdated) Get() *EventSessionUpdated {
	return v.value
}

func (v *NullableEventSessionUpdated) Set(val *EventSessionUpdated) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSessionUpdated) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSessionUpdated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSessionUpdated(val *EventSessionUpdated) *NullableEventSessionUpdated {
	return &NullableEventSessionUpdated{value: val, isSet: true}
}

func (v NullableEventSessionUpdated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSessionUpdated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


