/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventSessionIdle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSessionIdle{}

// EventSessionIdle struct for EventSessionIdle
type EventSessionIdle struct {
	Type string `json:"type"`
	Properties EventSessionIdleProperties `json:"properties"`
}

type _EventSessionIdle EventSessionIdle

// NewEventSessionIdle instantiates a new EventSessionIdle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSessionIdle(type_ string, properties EventSessionIdleProperties) *EventSessionIdle {
	this := EventSessionIdle{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventSessionIdleWithDefaults instantiates a new EventSessionIdle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSessionIdleWithDefaults() *EventSessionIdle {
	this := EventSessionIdle{}
	return &this
}

// GetType returns the Type field value
func (o *EventSessionIdle) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventSessionIdle) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventSessionIdle) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventSessionIdle) GetProperties() EventSessionIdleProperties {
	if o == nil {
		var ret EventSessionIdleProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventSessionIdle) GetPropertiesOk() (*EventSessionIdleProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventSessionIdle) SetProperties(v EventSessionIdleProperties) {
	o.Properties = v
}

func (o EventSessionIdle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSessionIdle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventSessionIdle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventSessionIdle := _EventSessionIdle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventSessionIdle)

	if err != nil {
		return err
	}

	*o = EventSessionIdle(varEventSessionIdle)

	return err
}

type NullableEventSessionIdle struct {
	value *EventSessionIdle
	isSet bool
}

func (v NullableEventSessionIdle) Get() *EventSessionIdle {
	return v.value
}

func (v *NullableEventSessionIdle) Set(val *EventSessionIdle) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSessionIdle) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSessionIdle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSessionIdle(val *EventSessionIdle) *NullableEventSessionIdle {
	return &NullableEventSessionIdle{value: val, isSet: true}
}

func (v NullableEventSessionIdle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSessionIdle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


