/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventStorageWrite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventStorageWrite{}

// EventStorageWrite struct for EventStorageWrite
type EventStorageWrite struct {
	Type string `json:"type"`
	Properties EventStorageWriteProperties `json:"properties"`
}

type _EventStorageWrite EventStorageWrite

// NewEventStorageWrite instantiates a new EventStorageWrite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventStorageWrite(type_ string, properties EventStorageWriteProperties) *EventStorageWrite {
	this := EventStorageWrite{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventStorageWriteWithDefaults instantiates a new EventStorageWrite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventStorageWriteWithDefaults() *EventStorageWrite {
	this := EventStorageWrite{}
	return &this
}

// GetType returns the Type field value
func (o *EventStorageWrite) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventStorageWrite) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventStorageWrite) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventStorageWrite) GetProperties() EventStorageWriteProperties {
	if o == nil {
		var ret EventStorageWriteProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventStorageWrite) GetPropertiesOk() (*EventStorageWriteProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventStorageWrite) SetProperties(v EventStorageWriteProperties) {
	o.Properties = v
}

func (o EventStorageWrite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventStorageWrite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventStorageWrite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventStorageWrite := _EventStorageWrite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventStorageWrite)

	if err != nil {
		return err
	}

	*o = EventStorageWrite(varEventStorageWrite)

	return err
}

type NullableEventStorageWrite struct {
	value *EventStorageWrite
	isSet bool
}

func (v NullableEventStorageWrite) Get() *EventStorageWrite {
	return v.value
}

func (v *NullableEventStorageWrite) Set(val *EventStorageWrite) {
	v.value = val
	v.isSet = true
}

func (v NullableEventStorageWrite) IsSet() bool {
	return v.isSet
}

func (v *NullableEventStorageWrite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventStorageWrite(val *EventStorageWrite) *NullableEventStorageWrite {
	return &NullableEventStorageWrite{value: val, isSet: true}
}

func (v NullableEventStorageWrite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventStorageWrite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


