/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventIdeInstalled type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventIdeInstalled{}

// EventIdeInstalled struct for EventIdeInstalled
type EventIdeInstalled struct {
	Type string `json:"type"`
	Properties EventIdeInstalledProperties `json:"properties"`
}

type _EventIdeInstalled EventIdeInstalled

// NewEventIdeInstalled instantiates a new EventIdeInstalled object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventIdeInstalled(type_ string, properties EventIdeInstalledProperties) *EventIdeInstalled {
	this := EventIdeInstalled{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventIdeInstalledWithDefaults instantiates a new EventIdeInstalled object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventIdeInstalledWithDefaults() *EventIdeInstalled {
	this := EventIdeInstalled{}
	return &this
}

// GetType returns the Type field value
func (o *EventIdeInstalled) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventIdeInstalled) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventIdeInstalled) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventIdeInstalled) GetProperties() EventIdeInstalledProperties {
	if o == nil {
		var ret EventIdeInstalledProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventIdeInstalled) GetPropertiesOk() (*EventIdeInstalledProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventIdeInstalled) SetProperties(v EventIdeInstalledProperties) {
	o.Properties = v
}

func (o EventIdeInstalled) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventIdeInstalled) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventIdeInstalled) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventIdeInstalled := _EventIdeInstalled{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventIdeInstalled)

	if err != nil {
		return err
	}

	*o = EventIdeInstalled(varEventIdeInstalled)

	return err
}

type NullableEventIdeInstalled struct {
	value *EventIdeInstalled
	isSet bool
}

func (v NullableEventIdeInstalled) Get() *EventIdeInstalled {
	return v.value
}

func (v *NullableEventIdeInstalled) Set(val *EventIdeInstalled) {
	v.value = val
	v.isSet = true
}

func (v NullableEventIdeInstalled) IsSet() bool {
	return v.isSet
}

func (v *NullableEventIdeInstalled) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventIdeInstalled(val *EventIdeInstalled) *NullableEventIdeInstalled {
	return &NullableEventIdeInstalled{value: val, isSet: true}
}

func (v NullableEventIdeInstalled) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventIdeInstalled) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


