/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigExperimentalHookFileEditedValueInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigExperimentalHookFileEditedValueInner{}

// ConfigExperimentalHookFileEditedValueInner struct for ConfigExperimentalHookFileEditedValueInner
type ConfigExperimentalHookFileEditedValueInner struct {
	Command []string `json:"command"`
	Environment *map[string]string `json:"environment,omitempty"`
}

type _ConfigExperimentalHookFileEditedValueInner ConfigExperimentalHookFileEditedValueInner

// NewConfigExperimentalHookFileEditedValueInner instantiates a new ConfigExperimentalHookFileEditedValueInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigExperimentalHookFileEditedValueInner(command []string) *ConfigExperimentalHookFileEditedValueInner {
	this := ConfigExperimentalHookFileEditedValueInner{}
	this.Command = command
	return &this
}

// NewConfigExperimentalHookFileEditedValueInnerWithDefaults instantiates a new ConfigExperimentalHookFileEditedValueInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigExperimentalHookFileEditedValueInnerWithDefaults() *ConfigExperimentalHookFileEditedValueInner {
	this := ConfigExperimentalHookFileEditedValueInner{}
	return &this
}

// GetCommand returns the Command field value
func (o *ConfigExperimentalHookFileEditedValueInner) GetCommand() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *ConfigExperimentalHookFileEditedValueInner) GetCommandOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command, true
}

// SetCommand sets field value
func (o *ConfigExperimentalHookFileEditedValueInner) SetCommand(v []string) {
	o.Command = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *ConfigExperimentalHookFileEditedValueInner) GetEnvironment() map[string]string {
	if o == nil || IsNil(o.Environment) {
		var ret map[string]string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigExperimentalHookFileEditedValueInner) GetEnvironmentOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *ConfigExperimentalHookFileEditedValueInner) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given map[string]string and assigns it to the Environment field.
func (o *ConfigExperimentalHookFileEditedValueInner) SetEnvironment(v map[string]string) {
	o.Environment = &v
}

func (o ConfigExperimentalHookFileEditedValueInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigExperimentalHookFileEditedValueInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	return toSerialize, nil
}

func (o *ConfigExperimentalHookFileEditedValueInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigExperimentalHookFileEditedValueInner := _ConfigExperimentalHookFileEditedValueInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigExperimentalHookFileEditedValueInner)

	if err != nil {
		return err
	}

	*o = ConfigExperimentalHookFileEditedValueInner(varConfigExperimentalHookFileEditedValueInner)

	return err
}

type NullableConfigExperimentalHookFileEditedValueInner struct {
	value *ConfigExperimentalHookFileEditedValueInner
	isSet bool
}

func (v NullableConfigExperimentalHookFileEditedValueInner) Get() *ConfigExperimentalHookFileEditedValueInner {
	return v.value
}

func (v *NullableConfigExperimentalHookFileEditedValueInner) Set(val *ConfigExperimentalHookFileEditedValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigExperimentalHookFileEditedValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigExperimentalHookFileEditedValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigExperimentalHookFileEditedValueInner(val *ConfigExperimentalHookFileEditedValueInner) *NullableConfigExperimentalHookFileEditedValueInner {
	return &NullableConfigExperimentalHookFileEditedValueInner{value: val, isSet: true}
}

func (v NullableConfigExperimentalHookFileEditedValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigExperimentalHookFileEditedValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


