/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SnapshotPart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnapshotPart{}

// SnapshotPart struct for SnapshotPart
type SnapshotPart struct {
	Id string `json:"id"`
	SessionID string `json:"sessionID"`
	MessageID string `json:"messageID"`
	Type string `json:"type"`
	Snapshot string `json:"snapshot"`
}

type _SnapshotPart SnapshotPart

// NewSnapshotPart instantiates a new SnapshotPart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotPart(id string, sessionID string, messageID string, type_ string, snapshot string) *SnapshotPart {
	this := SnapshotPart{}
	this.Id = id
	this.SessionID = sessionID
	this.MessageID = messageID
	this.Type = type_
	this.Snapshot = snapshot
	return &this
}

// NewSnapshotPartWithDefaults instantiates a new SnapshotPart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotPartWithDefaults() *SnapshotPart {
	this := SnapshotPart{}
	return &this
}

// GetId returns the Id field value
func (o *SnapshotPart) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SnapshotPart) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SnapshotPart) SetId(v string) {
	o.Id = v
}

// GetSessionID returns the SessionID field value
func (o *SnapshotPart) GetSessionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionID
}

// GetSessionIDOk returns a tuple with the SessionID field value
// and a boolean to check if the value has been set.
func (o *SnapshotPart) GetSessionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionID, true
}

// SetSessionID sets field value
func (o *SnapshotPart) SetSessionID(v string) {
	o.SessionID = v
}

// GetMessageID returns the MessageID field value
func (o *SnapshotPart) GetMessageID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageID
}

// GetMessageIDOk returns a tuple with the MessageID field value
// and a boolean to check if the value has been set.
func (o *SnapshotPart) GetMessageIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageID, true
}

// SetMessageID sets field value
func (o *SnapshotPart) SetMessageID(v string) {
	o.MessageID = v
}

// GetType returns the Type field value
func (o *SnapshotPart) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SnapshotPart) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SnapshotPart) SetType(v string) {
	o.Type = v
}

// GetSnapshot returns the Snapshot field value
func (o *SnapshotPart) GetSnapshot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Snapshot
}

// GetSnapshotOk returns a tuple with the Snapshot field value
// and a boolean to check if the value has been set.
func (o *SnapshotPart) GetSnapshotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Snapshot, true
}

// SetSnapshot sets field value
func (o *SnapshotPart) SetSnapshot(v string) {
	o.Snapshot = v
}

func (o SnapshotPart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnapshotPart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["sessionID"] = o.SessionID
	toSerialize["messageID"] = o.MessageID
	toSerialize["type"] = o.Type
	toSerialize["snapshot"] = o.Snapshot
	return toSerialize, nil
}

func (o *SnapshotPart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"sessionID",
		"messageID",
		"type",
		"snapshot",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnapshotPart := _SnapshotPart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnapshotPart)

	if err != nil {
		return err
	}

	*o = SnapshotPart(varSnapshotPart)

	return err
}

type NullableSnapshotPart struct {
	value *SnapshotPart
	isSet bool
}

func (v NullableSnapshotPart) Get() *SnapshotPart {
	return v.value
}

func (v *NullableSnapshotPart) Set(val *SnapshotPart) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotPart) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotPart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotPart(val *SnapshotPart) *NullableSnapshotPart {
	return &NullableSnapshotPart{value: val, isSet: true}
}

func (v NullableSnapshotPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotPart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


