/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnknownErrorData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnknownErrorData{}

// UnknownErrorData struct for UnknownErrorData
type UnknownErrorData struct {
	Message string `json:"message"`
}

type _UnknownErrorData UnknownErrorData

// NewUnknownErrorData instantiates a new UnknownErrorData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnknownErrorData(message string) *UnknownErrorData {
	this := UnknownErrorData{}
	this.Message = message
	return &this
}

// NewUnknownErrorDataWithDefaults instantiates a new UnknownErrorData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnknownErrorDataWithDefaults() *UnknownErrorData {
	this := UnknownErrorData{}
	return &this
}

// GetMessage returns the Message field value
func (o *UnknownErrorData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UnknownErrorData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UnknownErrorData) SetMessage(v string) {
	o.Message = v
}

func (o UnknownErrorData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnknownErrorData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *UnknownErrorData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnknownErrorData := _UnknownErrorData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnknownErrorData)

	if err != nil {
		return err
	}

	*o = UnknownErrorData(varUnknownErrorData)

	return err
}

type NullableUnknownErrorData struct {
	value *UnknownErrorData
	isSet bool
}

func (v NullableUnknownErrorData) Get() *UnknownErrorData {
	return v.value
}

func (v *NullableUnknownErrorData) Set(val *UnknownErrorData) {
	v.value = val
	v.isSet = true
}

func (v NullableUnknownErrorData) IsSet() bool {
	return v.isSet
}

func (v *NullableUnknownErrorData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnknownErrorData(val *UnknownErrorData) *NullableUnknownErrorData {
	return &NullableUnknownErrorData{value: val, isSet: true}
}

func (v NullableUnknownErrorData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnknownErrorData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


