/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssistantMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantMessage{}

// AssistantMessage struct for AssistantMessage
type AssistantMessage struct {
	Id string `json:"id"`
	SessionID string `json:"sessionID"`
	Role string `json:"role"`
	Time AssistantMessageTime `json:"time"`
	Error *AssistantMessageError `json:"error,omitempty"`
	System []string `json:"system"`
	ModelID string `json:"modelID"`
	ProviderID string `json:"providerID"`
	Path AssistantMessagePath `json:"path"`
	Summary *bool `json:"summary,omitempty"`
	Cost float32 `json:"cost"`
	Tokens AssistantMessageTokens `json:"tokens"`
}

type _AssistantMessage AssistantMessage

// NewAssistantMessage instantiates a new AssistantMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantMessage(id string, sessionID string, role string, time AssistantMessageTime, system []string, modelID string, providerID string, path AssistantMessagePath, cost float32, tokens AssistantMessageTokens) *AssistantMessage {
	this := AssistantMessage{}
	this.Id = id
	this.SessionID = sessionID
	this.Role = role
	this.Time = time
	this.System = system
	this.ModelID = modelID
	this.ProviderID = providerID
	this.Path = path
	this.Cost = cost
	this.Tokens = tokens
	return &this
}

// NewAssistantMessageWithDefaults instantiates a new AssistantMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantMessageWithDefaults() *AssistantMessage {
	this := AssistantMessage{}
	return &this
}

// GetId returns the Id field value
func (o *AssistantMessage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AssistantMessage) SetId(v string) {
	o.Id = v
}

// GetSessionID returns the SessionID field value
func (o *AssistantMessage) GetSessionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionID
}

// GetSessionIDOk returns a tuple with the SessionID field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetSessionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionID, true
}

// SetSessionID sets field value
func (o *AssistantMessage) SetSessionID(v string) {
	o.SessionID = v
}

// GetRole returns the Role field value
func (o *AssistantMessage) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *AssistantMessage) SetRole(v string) {
	o.Role = v
}

// GetTime returns the Time field value
func (o *AssistantMessage) GetTime() AssistantMessageTime {
	if o == nil {
		var ret AssistantMessageTime
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetTimeOk() (*AssistantMessageTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *AssistantMessage) SetTime(v AssistantMessageTime) {
	o.Time = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AssistantMessage) GetError() AssistantMessageError {
	if o == nil || IsNil(o.Error) {
		var ret AssistantMessageError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetErrorOk() (*AssistantMessageError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AssistantMessage) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given AssistantMessageError and assigns it to the Error field.
func (o *AssistantMessage) SetError(v AssistantMessageError) {
	o.Error = &v
}

// GetSystem returns the System field value
func (o *AssistantMessage) GetSystem() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.System
}

// GetSystemOk returns a tuple with the System field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetSystemOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.System, true
}

// SetSystem sets field value
func (o *AssistantMessage) SetSystem(v []string) {
	o.System = v
}

// GetModelID returns the ModelID field value
func (o *AssistantMessage) GetModelID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelID
}

// GetModelIDOk returns a tuple with the ModelID field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetModelIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelID, true
}

// SetModelID sets field value
func (o *AssistantMessage) SetModelID(v string) {
	o.ModelID = v
}

// GetProviderID returns the ProviderID field value
func (o *AssistantMessage) GetProviderID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderID
}

// GetProviderIDOk returns a tuple with the ProviderID field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetProviderIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderID, true
}

// SetProviderID sets field value
func (o *AssistantMessage) SetProviderID(v string) {
	o.ProviderID = v
}

// GetPath returns the Path field value
func (o *AssistantMessage) GetPath() AssistantMessagePath {
	if o == nil {
		var ret AssistantMessagePath
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetPathOk() (*AssistantMessagePath, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *AssistantMessage) SetPath(v AssistantMessagePath) {
	o.Path = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *AssistantMessage) GetSummary() bool {
	if o == nil || IsNil(o.Summary) {
		var ret bool
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetSummaryOk() (*bool, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *AssistantMessage) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given bool and assigns it to the Summary field.
func (o *AssistantMessage) SetSummary(v bool) {
	o.Summary = &v
}

// GetCost returns the Cost field value
func (o *AssistantMessage) GetCost() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cost
}

// GetCostOk returns a tuple with the Cost field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cost, true
}

// SetCost sets field value
func (o *AssistantMessage) SetCost(v float32) {
	o.Cost = v
}

// GetTokens returns the Tokens field value
func (o *AssistantMessage) GetTokens() AssistantMessageTokens {
	if o == nil {
		var ret AssistantMessageTokens
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *AssistantMessage) GetTokensOk() (*AssistantMessageTokens, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tokens, true
}

// SetTokens sets field value
func (o *AssistantMessage) SetTokens(v AssistantMessageTokens) {
	o.Tokens = v
}

func (o AssistantMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["sessionID"] = o.SessionID
	toSerialize["role"] = o.Role
	toSerialize["time"] = o.Time
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["system"] = o.System
	toSerialize["modelID"] = o.ModelID
	toSerialize["providerID"] = o.ProviderID
	toSerialize["path"] = o.Path
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	toSerialize["cost"] = o.Cost
	toSerialize["tokens"] = o.Tokens
	return toSerialize, nil
}

func (o *AssistantMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"sessionID",
		"role",
		"time",
		"system",
		"modelID",
		"providerID",
		"path",
		"cost",
		"tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssistantMessage := _AssistantMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssistantMessage)

	if err != nil {
		return err
	}

	*o = AssistantMessage(varAssistantMessage)

	return err
}

type NullableAssistantMessage struct {
	value *AssistantMessage
	isSet bool
}

func (v NullableAssistantMessage) Get() *AssistantMessage {
	return v.value
}

func (v *NullableAssistantMessage) Set(val *AssistantMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantMessage(val *AssistantMessage) *NullableAssistantMessage {
	return &NullableAssistantMessage{value: val, isSet: true}
}

func (v NullableAssistantMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


