/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventPermissionUpdated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventPermissionUpdated{}

// EventPermissionUpdated struct for EventPermissionUpdated
type EventPermissionUpdated struct {
	Type string `json:"type"`
	Properties PermissionInfo `json:"properties"`
}

type _EventPermissionUpdated EventPermissionUpdated

// NewEventPermissionUpdated instantiates a new EventPermissionUpdated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventPermissionUpdated(type_ string, properties PermissionInfo) *EventPermissionUpdated {
	this := EventPermissionUpdated{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventPermissionUpdatedWithDefaults instantiates a new EventPermissionUpdated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventPermissionUpdatedWithDefaults() *EventPermissionUpdated {
	this := EventPermissionUpdated{}
	return &this
}

// GetType returns the Type field value
func (o *EventPermissionUpdated) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventPermissionUpdated) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventPermissionUpdated) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventPermissionUpdated) GetProperties() PermissionInfo {
	if o == nil {
		var ret PermissionInfo
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventPermissionUpdated) GetPropertiesOk() (*PermissionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventPermissionUpdated) SetProperties(v PermissionInfo) {
	o.Properties = v
}

func (o EventPermissionUpdated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventPermissionUpdated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventPermissionUpdated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventPermissionUpdated := _EventPermissionUpdated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventPermissionUpdated)

	if err != nil {
		return err
	}

	*o = EventPermissionUpdated(varEventPermissionUpdated)

	return err
}

type NullableEventPermissionUpdated struct {
	value *EventPermissionUpdated
	isSet bool
}

func (v NullableEventPermissionUpdated) Get() *EventPermissionUpdated {
	return v.value
}

func (v *NullableEventPermissionUpdated) Set(val *EventPermissionUpdated) {
	v.value = val
	v.isSet = true
}

func (v NullableEventPermissionUpdated) IsSet() bool {
	return v.isSet
}

func (v *NullableEventPermissionUpdated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventPermissionUpdated(val *EventPermissionUpdated) *NullableEventPermissionUpdated {
	return &NullableEventPermissionUpdated{value: val, isSet: true}
}

func (v NullableEventPermissionUpdated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventPermissionUpdated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


