/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventMessageUpdated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventMessageUpdated{}

// EventMessageUpdated struct for EventMessageUpdated
type EventMessageUpdated struct {
	Type string `json:"type"`
	Properties EventMessageUpdatedProperties `json:"properties"`
}

type _EventMessageUpdated EventMessageUpdated

// NewEventMessageUpdated instantiates a new EventMessageUpdated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventMessageUpdated(type_ string, properties EventMessageUpdatedProperties) *EventMessageUpdated {
	this := EventMessageUpdated{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventMessageUpdatedWithDefaults instantiates a new EventMessageUpdated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventMessageUpdatedWithDefaults() *EventMessageUpdated {
	this := EventMessageUpdated{}
	return &this
}

// GetType returns the Type field value
func (o *EventMessageUpdated) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventMessageUpdated) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventMessageUpdated) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventMessageUpdated) GetProperties() EventMessageUpdatedProperties {
	if o == nil {
		var ret EventMessageUpdatedProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventMessageUpdated) GetPropertiesOk() (*EventMessageUpdatedProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventMessageUpdated) SetProperties(v EventMessageUpdatedProperties) {
	o.Properties = v
}

func (o EventMessageUpdated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventMessageUpdated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventMessageUpdated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventMessageUpdated := _EventMessageUpdated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventMessageUpdated)

	if err != nil {
		return err
	}

	*o = EventMessageUpdated(varEventMessageUpdated)

	return err
}

type NullableEventMessageUpdated struct {
	value *EventMessageUpdated
	isSet bool
}

func (v NullableEventMessageUpdated) Get() *EventMessageUpdated {
	return v.value
}

func (v *NullableEventMessageUpdated) Set(val *EventMessageUpdated) {
	v.value = val
	v.isSet = true
}

func (v NullableEventMessageUpdated) IsSet() bool {
	return v.isSet
}

func (v *NullableEventMessageUpdated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventMessageUpdated(val *EventMessageUpdated) *NullableEventMessageUpdated {
	return &NullableEventMessageUpdated{value: val, isSet: true}
}

func (v NullableEventMessageUpdated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventMessageUpdated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


