/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProviderAuthError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderAuthError{}

// ProviderAuthError struct for ProviderAuthError
type ProviderAuthError struct {
	Name string `json:"name"`
	Data ProviderAuthErrorData `json:"data"`
}

type _ProviderAuthError ProviderAuthError

// NewProviderAuthError instantiates a new ProviderAuthError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderAuthError(name string, data ProviderAuthErrorData) *ProviderAuthError {
	this := ProviderAuthError{}
	this.Name = name
	this.Data = data
	return &this
}

// NewProviderAuthErrorWithDefaults instantiates a new ProviderAuthError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderAuthErrorWithDefaults() *ProviderAuthError {
	this := ProviderAuthError{}
	return &this
}

// GetName returns the Name field value
func (o *ProviderAuthError) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProviderAuthError) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProviderAuthError) SetName(v string) {
	o.Name = v
}

// GetData returns the Data field value
func (o *ProviderAuthError) GetData() ProviderAuthErrorData {
	if o == nil {
		var ret ProviderAuthErrorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ProviderAuthError) GetDataOk() (*ProviderAuthErrorData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ProviderAuthError) SetData(v ProviderAuthErrorData) {
	o.Data = v
}

func (o ProviderAuthError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderAuthError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ProviderAuthError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderAuthError := _ProviderAuthError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderAuthError)

	if err != nil {
		return err
	}

	*o = ProviderAuthError(varProviderAuthError)

	return err
}

type NullableProviderAuthError struct {
	value *ProviderAuthError
	isSet bool
}

func (v NullableProviderAuthError) Get() *ProviderAuthError {
	return v.value
}

func (v *NullableProviderAuthError) Set(val *ProviderAuthError) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderAuthError) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderAuthError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderAuthError(val *ProviderAuthError) *NullableProviderAuthError {
	return &NullableProviderAuthError{value: val, isSet: true}
}

func (v NullableProviderAuthError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderAuthError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


