/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionShare type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionShare{}

// SessionShare struct for SessionShare
type SessionShare struct {
	Url string `json:"url"`
}

type _SessionShare SessionShare

// NewSessionShare instantiates a new SessionShare object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionShare(url string) *SessionShare {
	this := SessionShare{}
	this.Url = url
	return &this
}

// NewSessionShareWithDefaults instantiates a new SessionShare object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionShareWithDefaults() *SessionShare {
	this := SessionShare{}
	return &this
}

// GetUrl returns the Url field value
func (o *SessionShare) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SessionShare) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SessionShare) SetUrl(v string) {
	o.Url = v
}

func (o SessionShare) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionShare) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *SessionShare) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionShare := _SessionShare{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionShare)

	if err != nil {
		return err
	}

	*o = SessionShare(varSessionShare)

	return err
}

type NullableSessionShare struct {
	value *SessionShare
	isSet bool
}

func (v NullableSessionShare) Get() *SessionShare {
	return v.value
}

func (v *NullableSessionShare) Set(val *SessionShare) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionShare) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionShare) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionShare(val *SessionShare) *NullableSessionShare {
	return &NullableSessionShare{value: val, isSet: true}
}

func (v NullableSessionShare) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionShare) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


