/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventMessagePartUpdated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventMessagePartUpdated{}

// EventMessagePartUpdated struct for EventMessagePartUpdated
type EventMessagePartUpdated struct {
	Type string `json:"type"`
	Properties EventMessagePartUpdatedProperties `json:"properties"`
}

type _EventMessagePartUpdated EventMessagePartUpdated

// NewEventMessagePartUpdated instantiates a new EventMessagePartUpdated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventMessagePartUpdated(type_ string, properties EventMessagePartUpdatedProperties) *EventMessagePartUpdated {
	this := EventMessagePartUpdated{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventMessagePartUpdatedWithDefaults instantiates a new EventMessagePartUpdated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventMessagePartUpdatedWithDefaults() *EventMessagePartUpdated {
	this := EventMessagePartUpdated{}
	return &this
}

// GetType returns the Type field value
func (o *EventMessagePartUpdated) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventMessagePartUpdated) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventMessagePartUpdated) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventMessagePartUpdated) GetProperties() EventMessagePartUpdatedProperties {
	if o == nil {
		var ret EventMessagePartUpdatedProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventMessagePartUpdated) GetPropertiesOk() (*EventMessagePartUpdatedProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventMessagePartUpdated) SetProperties(v EventMessagePartUpdatedProperties) {
	o.Properties = v
}

func (o EventMessagePartUpdated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventMessagePartUpdated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventMessagePartUpdated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventMessagePartUpdated := _EventMessagePartUpdated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventMessagePartUpdated)

	if err != nil {
		return err
	}

	*o = EventMessagePartUpdated(varEventMessagePartUpdated)

	return err
}

type NullableEventMessagePartUpdated struct {
	value *EventMessagePartUpdated
	isSet bool
}

func (v NullableEventMessagePartUpdated) Get() *EventMessagePartUpdated {
	return v.value
}

func (v *NullableEventMessagePartUpdated) Set(val *EventMessagePartUpdated) {
	v.value = val
	v.isSet = true
}

func (v NullableEventMessagePartUpdated) IsSet() bool {
	return v.isSet
}

func (v *NullableEventMessagePartUpdated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventMessagePartUpdated(val *EventMessagePartUpdated) *NullableEventMessagePartUpdated {
	return &NullableEventMessagePartUpdated{value: val, isSet: true}
}

func (v NullableEventMessagePartUpdated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventMessagePartUpdated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


