/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigProviderValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigProviderValue{}

// ConfigProviderValue struct for ConfigProviderValue
type ConfigProviderValue struct {
	Api *string `json:"api,omitempty"`
	Name *string `json:"name,omitempty"`
	Env []string `json:"env,omitempty"`
	Id *string `json:"id,omitempty"`
	Npm *string `json:"npm,omitempty"`
	Models map[string]ConfigProviderValueModelsValue `json:"models"`
	Options map[string]interface{} `json:"options,omitempty"`
}

type _ConfigProviderValue ConfigProviderValue

// NewConfigProviderValue instantiates a new ConfigProviderValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigProviderValue(models map[string]ConfigProviderValueModelsValue) *ConfigProviderValue {
	this := ConfigProviderValue{}
	this.Models = models
	return &this
}

// NewConfigProviderValueWithDefaults instantiates a new ConfigProviderValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigProviderValueWithDefaults() *ConfigProviderValue {
	this := ConfigProviderValue{}
	return &this
}

// GetApi returns the Api field value if set, zero value otherwise.
func (o *ConfigProviderValue) GetApi() string {
	if o == nil || IsNil(o.Api) {
		var ret string
		return ret
	}
	return *o.Api
}

// GetApiOk returns a tuple with the Api field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetApiOk() (*string, bool) {
	if o == nil || IsNil(o.Api) {
		return nil, false
	}
	return o.Api, true
}

// HasApi returns a boolean if a field has been set.
func (o *ConfigProviderValue) HasApi() bool {
	if o != nil && !IsNil(o.Api) {
		return true
	}

	return false
}

// SetApi gets a reference to the given string and assigns it to the Api field.
func (o *ConfigProviderValue) SetApi(v string) {
	o.Api = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigProviderValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigProviderValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigProviderValue) SetName(v string) {
	o.Name = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *ConfigProviderValue) GetEnv() []string {
	if o == nil || IsNil(o.Env) {
		var ret []string
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetEnvOk() ([]string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *ConfigProviderValue) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []string and assigns it to the Env field.
func (o *ConfigProviderValue) SetEnv(v []string) {
	o.Env = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ConfigProviderValue) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ConfigProviderValue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ConfigProviderValue) SetId(v string) {
	o.Id = &v
}

// GetNpm returns the Npm field value if set, zero value otherwise.
func (o *ConfigProviderValue) GetNpm() string {
	if o == nil || IsNil(o.Npm) {
		var ret string
		return ret
	}
	return *o.Npm
}

// GetNpmOk returns a tuple with the Npm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetNpmOk() (*string, bool) {
	if o == nil || IsNil(o.Npm) {
		return nil, false
	}
	return o.Npm, true
}

// HasNpm returns a boolean if a field has been set.
func (o *ConfigProviderValue) HasNpm() bool {
	if o != nil && !IsNil(o.Npm) {
		return true
	}

	return false
}

// SetNpm gets a reference to the given string and assigns it to the Npm field.
func (o *ConfigProviderValue) SetNpm(v string) {
	o.Npm = &v
}

// GetModels returns the Models field value
func (o *ConfigProviderValue) GetModels() map[string]ConfigProviderValueModelsValue {
	if o == nil {
		var ret map[string]ConfigProviderValueModelsValue
		return ret
	}

	return o.Models
}

// GetModelsOk returns a tuple with the Models field value
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetModelsOk() (*map[string]ConfigProviderValueModelsValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Models, true
}

// SetModels sets field value
func (o *ConfigProviderValue) SetModels(v map[string]ConfigProviderValueModelsValue) {
	o.Models = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *ConfigProviderValue) GetOptions() map[string]interface{} {
	if o == nil || IsNil(o.Options) {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigProviderValue) GetOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return map[string]interface{}{}, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *ConfigProviderValue) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *ConfigProviderValue) SetOptions(v map[string]interface{}) {
	o.Options = v
}

func (o ConfigProviderValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigProviderValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Api) {
		toSerialize["api"] = o.Api
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Npm) {
		toSerialize["npm"] = o.Npm
	}
	toSerialize["models"] = o.Models
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

func (o *ConfigProviderValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"models",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigProviderValue := _ConfigProviderValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigProviderValue)

	if err != nil {
		return err
	}

	*o = ConfigProviderValue(varConfigProviderValue)

	return err
}

type NullableConfigProviderValue struct {
	value *ConfigProviderValue
	isSet bool
}

func (v NullableConfigProviderValue) Get() *ConfigProviderValue {
	return v.value
}

func (v *NullableConfigProviderValue) Set(val *ConfigProviderValue) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigProviderValue) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigProviderValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigProviderValue(val *ConfigProviderValue) *NullableConfigProviderValue {
	return &NullableConfigProviderValue{value: val, isSet: true}
}

func (v NullableConfigProviderValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigProviderValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


