/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StepStartPart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StepStartPart{}

// StepStartPart struct for StepStartPart
type StepStartPart struct {
	Id string `json:"id"`
	SessionID string `json:"sessionID"`
	MessageID string `json:"messageID"`
	Type string `json:"type"`
}

type _StepStartPart StepStartPart

// NewStepStartPart instantiates a new StepStartPart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStepStartPart(id string, sessionID string, messageID string, type_ string) *StepStartPart {
	this := StepStartPart{}
	this.Id = id
	this.SessionID = sessionID
	this.MessageID = messageID
	this.Type = type_
	return &this
}

// NewStepStartPartWithDefaults instantiates a new StepStartPart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStepStartPartWithDefaults() *StepStartPart {
	this := StepStartPart{}
	return &this
}

// GetId returns the Id field value
func (o *StepStartPart) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *StepStartPart) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *StepStartPart) SetId(v string) {
	o.Id = v
}

// GetSessionID returns the SessionID field value
func (o *StepStartPart) GetSessionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionID
}

// GetSessionIDOk returns a tuple with the SessionID field value
// and a boolean to check if the value has been set.
func (o *StepStartPart) GetSessionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionID, true
}

// SetSessionID sets field value
func (o *StepStartPart) SetSessionID(v string) {
	o.SessionID = v
}

// GetMessageID returns the MessageID field value
func (o *StepStartPart) GetMessageID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageID
}

// GetMessageIDOk returns a tuple with the MessageID field value
// and a boolean to check if the value has been set.
func (o *StepStartPart) GetMessageIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageID, true
}

// SetMessageID sets field value
func (o *StepStartPart) SetMessageID(v string) {
	o.MessageID = v
}

// GetType returns the Type field value
func (o *StepStartPart) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StepStartPart) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StepStartPart) SetType(v string) {
	o.Type = v
}

func (o StepStartPart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StepStartPart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["sessionID"] = o.SessionID
	toSerialize["messageID"] = o.MessageID
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StepStartPart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"sessionID",
		"messageID",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStepStartPart := _StepStartPart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStepStartPart)

	if err != nil {
		return err
	}

	*o = StepStartPart(varStepStartPart)

	return err
}

type NullableStepStartPart struct {
	value *StepStartPart
	isSet bool
}

func (v NullableStepStartPart) Get() *StepStartPart {
	return v.value
}

func (v *NullableStepStartPart) Set(val *StepStartPart) {
	v.value = val
	v.isSet = true
}

func (v NullableStepStartPart) IsSet() bool {
	return v.isSet
}

func (v *NullableStepStartPart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStepStartPart(val *StepStartPart) *NullableStepStartPart {
	return &NullableStepStartPart{value: val, isSet: true}
}

func (v NullableStepStartPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStepStartPart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


