/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventLspClientDiagnostics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventLspClientDiagnostics{}

// EventLspClientDiagnostics struct for EventLspClientDiagnostics
type EventLspClientDiagnostics struct {
	Type string `json:"type"`
	Properties EventLspClientDiagnosticsProperties `json:"properties"`
}

type _EventLspClientDiagnostics EventLspClientDiagnostics

// NewEventLspClientDiagnostics instantiates a new EventLspClientDiagnostics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventLspClientDiagnostics(type_ string, properties EventLspClientDiagnosticsProperties) *EventLspClientDiagnostics {
	this := EventLspClientDiagnostics{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventLspClientDiagnosticsWithDefaults instantiates a new EventLspClientDiagnostics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventLspClientDiagnosticsWithDefaults() *EventLspClientDiagnostics {
	this := EventLspClientDiagnostics{}
	return &this
}

// GetType returns the Type field value
func (o *EventLspClientDiagnostics) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventLspClientDiagnostics) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventLspClientDiagnostics) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventLspClientDiagnostics) GetProperties() EventLspClientDiagnosticsProperties {
	if o == nil {
		var ret EventLspClientDiagnosticsProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventLspClientDiagnostics) GetPropertiesOk() (*EventLspClientDiagnosticsProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventLspClientDiagnostics) SetProperties(v EventLspClientDiagnosticsProperties) {
	o.Properties = v
}

func (o EventLspClientDiagnostics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventLspClientDiagnostics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventLspClientDiagnostics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventLspClientDiagnostics := _EventLspClientDiagnostics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventLspClientDiagnostics)

	if err != nil {
		return err
	}

	*o = EventLspClientDiagnostics(varEventLspClientDiagnostics)

	return err
}

type NullableEventLspClientDiagnostics struct {
	value *EventLspClientDiagnostics
	isSet bool
}

func (v NullableEventLspClientDiagnostics) Get() *EventLspClientDiagnostics {
	return v.value
}

func (v *NullableEventLspClientDiagnostics) Set(val *EventLspClientDiagnostics) {
	v.value = val
	v.isSet = true
}

func (v NullableEventLspClientDiagnostics) IsSet() bool {
	return v.isSet
}

func (v *NullableEventLspClientDiagnostics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventLspClientDiagnostics(val *EventLspClientDiagnostics) *NullableEventLspClientDiagnostics {
	return &NullableEventLspClientDiagnostics{value: val, isSet: true}
}

func (v NullableEventLspClientDiagnostics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventLspClientDiagnostics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


