/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventFileWatcherUpdated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventFileWatcherUpdated{}

// EventFileWatcherUpdated struct for EventFileWatcherUpdated
type EventFileWatcherUpdated struct {
	Type string `json:"type"`
	Properties EventFileWatcherUpdatedProperties `json:"properties"`
}

type _EventFileWatcherUpdated EventFileWatcherUpdated

// NewEventFileWatcherUpdated instantiates a new EventFileWatcherUpdated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventFileWatcherUpdated(type_ string, properties EventFileWatcherUpdatedProperties) *EventFileWatcherUpdated {
	this := EventFileWatcherUpdated{}
	this.Type = type_
	this.Properties = properties
	return &this
}

// NewEventFileWatcherUpdatedWithDefaults instantiates a new EventFileWatcherUpdated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventFileWatcherUpdatedWithDefaults() *EventFileWatcherUpdated {
	this := EventFileWatcherUpdated{}
	return &this
}

// GetType returns the Type field value
func (o *EventFileWatcherUpdated) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventFileWatcherUpdated) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventFileWatcherUpdated) SetType(v string) {
	o.Type = v
}

// GetProperties returns the Properties field value
func (o *EventFileWatcherUpdated) GetProperties() EventFileWatcherUpdatedProperties {
	if o == nil {
		var ret EventFileWatcherUpdatedProperties
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *EventFileWatcherUpdated) GetPropertiesOk() (*EventFileWatcherUpdatedProperties, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *EventFileWatcherUpdated) SetProperties(v EventFileWatcherUpdatedProperties) {
	o.Properties = v
}

func (o EventFileWatcherUpdated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventFileWatcherUpdated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *EventFileWatcherUpdated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventFileWatcherUpdated := _EventFileWatcherUpdated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventFileWatcherUpdated)

	if err != nil {
		return err
	}

	*o = EventFileWatcherUpdated(varEventFileWatcherUpdated)

	return err
}

type NullableEventFileWatcherUpdated struct {
	value *EventFileWatcherUpdated
	isSet bool
}

func (v NullableEventFileWatcherUpdated) Get() *EventFileWatcherUpdated {
	return v.value
}

func (v *NullableEventFileWatcherUpdated) Set(val *EventFileWatcherUpdated) {
	v.value = val
	v.isSet = true
}

func (v NullableEventFileWatcherUpdated) IsSet() bool {
	return v.isSet
}

func (v *NullableEventFileWatcherUpdated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventFileWatcherUpdated(val *EventFileWatcherUpdated) *NullableEventFileWatcherUpdated {
	return &NullableEventFileWatcherUpdated{value: val, isSet: true}
}

func (v NullableEventFileWatcherUpdated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventFileWatcherUpdated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


