/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTuiPromptRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTuiPromptRequest{}

// PostTuiPromptRequest struct for PostTuiPromptRequest
type PostTuiPromptRequest struct {
	Text string `json:"text"`
	Parts []Part `json:"parts"`
}

type _PostTuiPromptRequest PostTuiPromptRequest

// NewPostTuiPromptRequest instantiates a new PostTuiPromptRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTuiPromptRequest(text string, parts []Part) *PostTuiPromptRequest {
	this := PostTuiPromptRequest{}
	this.Text = text
	this.Parts = parts
	return &this
}

// NewPostTuiPromptRequestWithDefaults instantiates a new PostTuiPromptRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTuiPromptRequestWithDefaults() *PostTuiPromptRequest {
	this := PostTuiPromptRequest{}
	return &this
}

// GetText returns the Text field value
func (o *PostTuiPromptRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PostTuiPromptRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PostTuiPromptRequest) SetText(v string) {
	o.Text = v
}

// GetParts returns the Parts field value
func (o *PostTuiPromptRequest) GetParts() []Part {
	if o == nil {
		var ret []Part
		return ret
	}

	return o.Parts
}

// GetPartsOk returns a tuple with the Parts field value
// and a boolean to check if the value has been set.
func (o *PostTuiPromptRequest) GetPartsOk() ([]Part, bool) {
	if o == nil {
		return nil, false
	}
	return o.Parts, true
}

// SetParts sets field value
func (o *PostTuiPromptRequest) SetParts(v []Part) {
	o.Parts = v
}

func (o PostTuiPromptRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTuiPromptRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["parts"] = o.Parts
	return toSerialize, nil
}

func (o *PostTuiPromptRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"parts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTuiPromptRequest := _PostTuiPromptRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTuiPromptRequest)

	if err != nil {
		return err
	}

	*o = PostTuiPromptRequest(varPostTuiPromptRequest)

	return err
}

type NullablePostTuiPromptRequest struct {
	value *PostTuiPromptRequest
	isSet bool
}

func (v NullablePostTuiPromptRequest) Get() *PostTuiPromptRequest {
	return v.value
}

func (v *NullablePostTuiPromptRequest) Set(val *PostTuiPromptRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTuiPromptRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTuiPromptRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTuiPromptRequest(val *PostTuiPromptRequest) *NullablePostTuiPromptRequest {
	return &NullablePostTuiPromptRequest{value: val, isSet: true}
}

func (v NullablePostTuiPromptRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTuiPromptRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


