/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolStateCompletedTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolStateCompletedTime{}

// ToolStateCompletedTime struct for ToolStateCompletedTime
type ToolStateCompletedTime struct {
	Start float32 `json:"start"`
	End float32 `json:"end"`
}

type _ToolStateCompletedTime ToolStateCompletedTime

// NewToolStateCompletedTime instantiates a new ToolStateCompletedTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolStateCompletedTime(start float32, end float32) *ToolStateCompletedTime {
	this := ToolStateCompletedTime{}
	this.Start = start
	this.End = end
	return &this
}

// NewToolStateCompletedTimeWithDefaults instantiates a new ToolStateCompletedTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolStateCompletedTimeWithDefaults() *ToolStateCompletedTime {
	this := ToolStateCompletedTime{}
	return &this
}

// GetStart returns the Start field value
func (o *ToolStateCompletedTime) GetStart() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompletedTime) GetStartOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *ToolStateCompletedTime) SetStart(v float32) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *ToolStateCompletedTime) GetEnd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *ToolStateCompletedTime) GetEndOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *ToolStateCompletedTime) SetEnd(v float32) {
	o.End = v
}

func (o ToolStateCompletedTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolStateCompletedTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

func (o *ToolStateCompletedTime) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start",
		"end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolStateCompletedTime := _ToolStateCompletedTime{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolStateCompletedTime)

	if err != nil {
		return err
	}

	*o = ToolStateCompletedTime(varToolStateCompletedTime)

	return err
}

type NullableToolStateCompletedTime struct {
	value *ToolStateCompletedTime
	isSet bool
}

func (v NullableToolStateCompletedTime) Get() *ToolStateCompletedTime {
	return v.value
}

func (v *NullableToolStateCompletedTime) Set(val *ToolStateCompletedTime) {
	v.value = val
	v.isSet = true
}

func (v NullableToolStateCompletedTime) IsSet() bool {
	return v.isSet
}

func (v *NullableToolStateCompletedTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolStateCompletedTime(val *ToolStateCompletedTime) *NullableToolStateCompletedTime {
	return &NullableToolStateCompletedTime{value: val, isSet: true}
}

func (v NullableToolStateCompletedTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolStateCompletedTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


