/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventFileEditedProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventFileEditedProperties{}

// EventFileEditedProperties struct for EventFileEditedProperties
type EventFileEditedProperties struct {
	File string `json:"file"`
}

type _EventFileEditedProperties EventFileEditedProperties

// NewEventFileEditedProperties instantiates a new EventFileEditedProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventFileEditedProperties(file string) *EventFileEditedProperties {
	this := EventFileEditedProperties{}
	this.File = file
	return &this
}

// NewEventFileEditedPropertiesWithDefaults instantiates a new EventFileEditedProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventFileEditedPropertiesWithDefaults() *EventFileEditedProperties {
	this := EventFileEditedProperties{}
	return &this
}

// GetFile returns the File field value
func (o *EventFileEditedProperties) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *EventFileEditedProperties) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *EventFileEditedProperties) SetFile(v string) {
	o.File = v
}

func (o EventFileEditedProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventFileEditedProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File
	return toSerialize, nil
}

func (o *EventFileEditedProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventFileEditedProperties := _EventFileEditedProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventFileEditedProperties)

	if err != nil {
		return err
	}

	*o = EventFileEditedProperties(varEventFileEditedProperties)

	return err
}

type NullableEventFileEditedProperties struct {
	value *EventFileEditedProperties
	isSet bool
}

func (v NullableEventFileEditedProperties) Get() *EventFileEditedProperties {
	return v.value
}

func (v *NullableEventFileEditedProperties) Set(val *EventFileEditedProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableEventFileEditedProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableEventFileEditedProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventFileEditedProperties(val *EventFileEditedProperties) *NullableEventFileEditedProperties {
	return &NullableEventFileEditedProperties{value: val, isSet: true}
}

func (v NullableEventFileEditedProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventFileEditedProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


