/*
kuucode

opencode api

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuucode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolStateRunningTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolStateRunningTime{}

// ToolStateRunningTime struct for ToolStateRunningTime
type ToolStateRunningTime struct {
	Start float32 `json:"start"`
}

type _ToolStateRunningTime ToolStateRunningTime

// NewToolStateRunningTime instantiates a new ToolStateRunningTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolStateRunningTime(start float32) *ToolStateRunningTime {
	this := ToolStateRunningTime{}
	this.Start = start
	return &this
}

// NewToolStateRunningTimeWithDefaults instantiates a new ToolStateRunningTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolStateRunningTimeWithDefaults() *ToolStateRunningTime {
	this := ToolStateRunningTime{}
	return &this
}

// GetStart returns the Start field value
func (o *ToolStateRunningTime) GetStart() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *ToolStateRunningTime) GetStartOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *ToolStateRunningTime) SetStart(v float32) {
	o.Start = v
}

func (o ToolStateRunningTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolStateRunningTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	return toSerialize, nil
}

func (o *ToolStateRunningTime) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolStateRunningTime := _ToolStateRunningTime{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolStateRunningTime)

	if err != nil {
		return err
	}

	*o = ToolStateRunningTime(varToolStateRunningTime)

	return err
}

type NullableToolStateRunningTime struct {
	value *ToolStateRunningTime
	isSet bool
}

func (v NullableToolStateRunningTime) Get() *ToolStateRunningTime {
	return v.value
}

func (v *NullableToolStateRunningTime) Set(val *ToolStateRunningTime) {
	v.value = val
	v.isSet = true
}

func (v NullableToolStateRunningTime) IsSet() bool {
	return v.isSet
}

func (v *NullableToolStateRunningTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolStateRunningTime(val *ToolStateRunningTime) *NullableToolStateRunningTime {
	return &NullableToolStateRunningTime{value: val, isSet: true}
}

func (v NullableToolStateRunningTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolStateRunningTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


