daemon:
  port: 8080
  log_level: info
  watch_paths:
    - .
  max_concurrent_tasks: 15
  self_audit_interval: 5m

claude:
  model: claude-sonnet-4
  max_tokens: 200000
  api_key: ${CLAUDE_CODE_OAUTH_TOKEN}
  rate_limits:
    requests_per_minute: 60

tui:
  refresh_rate: 100ms
  theme: dark
  panels:
    - status
    - logs
    - tasks
    - diagnostics

hotreload:
  enabled: true
  debounce: 500ms
  backup_count: 5

ai:
  enabled: true
  provider: claude-cli  # Back to CLI for real fixes
  auto_implement_todos: true
  auto_fix_issues: true
  require_approval: false
  safety_level: balanced
  enabled_issue_types:
    - todo_comment
    - missing_error_handling
    - missing_return
    - unused_variable
  max_changes_per_run: 50
  generate_tests: true
  use_sequential_thinking: true
  use_mcp_tools: true