name: "kuuzuki GitHub Action"
description: "Run kuuzuki in GitHub Actions workflows"
branding:
  icon: "code"
  color: "orange"

inputs:
  model:
    description: "Model to use"
    required: true

  share:
    description: "Share the kuuzuki session (defaults to true for public repos)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install kuuzuki
      shell: bash
      run: curl -fsSL https://kuuzuki.com/install | bash

    - name: Run kuuzuki
      shell: bash
      id: run_kuuzuki
      run: kuuzuki github run
      env:
        MODEL: ${{ inputs.model }}
        SHARE: ${{ inputs.share }}
