name: Build Desktop App

on:
  push:
    branches: [ main, kuuzuki-clean-final ]
  pull_request:
    branches: [ main ]

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-22.04
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.rust_target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.platform.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install frontend dependencies
        run: bun install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: packages/desktop
          args: --target ${{ matrix.platform.rust_target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kuuzuki-desktop-${{ matrix.platform.rust_target }}
          path: |
            packages/desktop/src-tauri/target/release/bundle/
            packages/desktop/src-tauri/target/release/*.exe
            packages/desktop/src-tauri/target/release/kuuzuki-desktop