name: Desktop Build

on:
  push:
    branches: [main]
    paths:
      - "packages/desktop/**"
      - "packages/tui/**"
      - ".github/workflows/desktop-build.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/desktop/**"
      - "packages/tui/**"
  workflow_dispatch:
    inputs:
      release:
        description: "Create release"
        required: false
        default: false
        type: boolean

jobs:
  build-desktop:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target universal-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./packages/desktop/src-tauri -> target"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install frontend dependencies
        run: bun install
        working-directory: packages/desktop

      - name: Build TUI
        run: |
          cd packages/tui
          go build -o kuucode-tui ./cmd/kuucode

      - name: Build frontend
        run: bun run build:web
        working-directory: packages/desktop

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: packages/desktop
          args: ${{ matrix.args }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kuucode-desktop-${{ matrix.platform }}
          path: |
            packages/desktop/src-tauri/target/release/bundle/
            packages/desktop/src-tauri/target/release/kuucode-desktop*
          retention-days: 30

  release:
    if: github.event.inputs.release == 'true' || (github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]'))
    needs: build-desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: desktop-v0.1.0-${{ github.run_number }}
          name: Kuucode Desktop v0.1.0-${{ github.run_number }}
          body: |
            ## Kuucode Desktop v0.1.0

            Cross-platform desktop application for Kuucode.

            ### Downloads
            - **Linux**: `.deb` and `.rpm` packages, plus `.AppImage`
            - **macOS**: Universal `.dmg` installer
            - **Windows**: `.msi` installer and portable `.exe`

            ### Installation
            - **Linux**: `sudo dpkg -i kuucode-desktop_*.deb` or `sudo rpm -i kuucode-desktop-*.rpm`
            - **macOS**: Open the `.dmg` and drag to Applications
            - **Windows**: Run the `.msi` installer

            Built from commit: ${{ github.sha }}
          files: |
            artifacts/**/*
          draft: false
          prerelease: true
